#!/bin/bash
## kola:
##   # Since we pull a container image
##   tags: "needs-internet"
##   timeoutMin: 30
##   description: Verify that rhel8 journalctl can still read our journals.
##     https://issues.redhat.com/browse/OCPBUGS-11492

set -euo pipefail

. $KOLA_EXT_DATA/commonlib.sh

cd $(mktemp -d)

# The string Linux should match the kernel boot
rc=0
podman run --privileged --net=none -v /var/log:/var/log:ro --rm registry.access.redhat.com/ubi8/ubi:latest journalctl -D /var/log/journal --grep="Linux" > journal.txt 2>err.txt || rc=$?
if [ "$rc" != 0 ]; then
    cat err.txt
    fatal "podman run exited with rc=$rc"
fi
if grep -qF 'uses an unsupported feature' err.txt; then
    fatal "Got unsupported feature trying to read journal"
fi
if ! grep -F "Linux" journal.txt; then
    fatal "Failed to read journal"
fi
