#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify /usr/bin/qemu-ga exists.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! test -f /usr/bin/qemu-ga; then
  fatal "Error: missing qemu guest agent"
fi
