#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify conntrack-tools is installed by default 
##     on RHCOS (not installed on FCOS).

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! rpm --quiet -q conntrack-tools; then
    fatal "Error: conntrack-tools is not installed"
fi
if test -f /usr/lib/systemd/system/conntrackd.service; then
    fatal "Error: conntrack tools should not have daemon"
fi
