#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify `kata-osbuilder-generate.service` is
##     part of the default presets, defined in
##     /usr/lib/systemd/system-preset/45-rhcos-extensions.preset
##     https://bugzilla.redhat.com/show_bug.cgi?id=1941342
##     https://github.com/openshift/os/pull/524

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

config="/usr/lib/systemd/system-preset/45-rhcos-extensions.preset"

service="enable kata-osbuilder-generate.service"
if ! grep -q "${service}" ${config}; then
    fatal "Error: missing '${service}' in ${config}"
fi
echo "ok verify '${service}' in ${config}"
