#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify /etc/localtime link exists.
##     https://github.com/openshift/os/pull/1021
##     https://issues.redhat.com/browse/LOG-3117

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

test -L /etc/localtime
