#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify CONFIG_RANDOM_TRUST_CPU is enabled by default.
##   architectures: x86_64

# This test can be removed when RHCOS gets to kernel version 6.2+
# https://github.com/coreos/fedora-coreos-tracker/issues/1369
# https://github.com/coreos/fedora-coreos-config/pull/2155
# https://bugzilla.redhat.com/show_bug.cgi?id=1830280

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

case "$(uname -r)" in
    5.*|6.0.*|6.1.*)
        config=$(grep ^CONFIG_RANDOM_TRUST_CPU /lib/modules/$(uname -r)/config)
        if [ "$config" != "CONFIG_RANDOM_TRUST_CPU=y" ]; then
            fatal "config missing CONFIG_RANDOM_TRUST_CPU"
        fi
        ok "random trust cpu" ;;
    *) echo "CPU trusting is always enabled" ;;
esac
