#!/bin/bash

# This is RHCOS only
# https://github.com/openshift/os/pull/672

# kola: { "exclusive": false }
set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if ! test -f /var/lib/.coreos-usrlocal-fixup.stamp; then
    fatal "Error: missing /var/lib/.coreos-usrlocal-fixup.stamp"
fi
