#!/bin/bash

# This is RHCOS only
# https://github.com/openshift/os/pull/672

# kola: { "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

if ! test -f /var/lib/.coreos-usrlocal-fixup.stamp; then
    fatal "Error: missing /var/lib/.coreos-usrlocal-fixup.stamp"
fi
