IMAGE_FROM=registry.ci.openshift.org/coreos/rhel-coreos-base:10.2

# The streamclass is based on the rhel/centos major version. The
# io.openshift.os.streamclass label is used by the MCO to later
# select the right image stream when multiple major versions coexist.
STREAM_CLASS=rhel-10

IMAGE_NAME=openshift/ose-rhel-coreos-10
IMAGE_CPE=cpe:/a:redhat:openshift:4.22::el10
