OPENSHIFT_VERSION=5.1
IMAGE_FROM=registry.ci.openshift.org/coreos/stream-coreos-base:10

# The streamclass is based on the rhel/centos major version. The
# io.openshift.os.streamclass label is used by the MCO to later
# select the right image stream when multiple major versions coexist.
#
# Currently there are not multiple streams for OKD, but we maintain
# this here for code symmetry with RHEL.
STREAM_CLASS=centos-10

# SCOS/OKD: no labels.json or OCI labels for name/cpe (so don't define them)
# IMAGE_NAME=
# IMAGE_CPE=

# The names of the yum repos to use for the node image build.
# XXX: use of the rhel-*server-ose-* ART repo shouldn't happen for OKD; see related XXX
#      in build-node-image.sh. Also we must put the ART repo last for the modification
#      in the script to work.
YUM_REPO_NAMES=c10s-baseos,c10s-appstream,c10s-sig-nfv,c10s-sig-cloud-okd,rhel-10.2-server-ose-5.1

# The extra yum repos (on top of the YUM_REPO_NAMES above) to use for
# the extensions image build.
#
# - c10s-nfv -> kernel-rt extension (x86_64 only)
#
# All other extensions can be pulled from the list of yum repos above.
EXTENSIONS_YUM_REPO_NAMES=c10s-nfv
