OPENSHIFT_VERSION=5.1
IMAGE_FROM=registry.ci.openshift.org/coreos/rhel-coreos-base:10.2

# The streamclass is based on the rhel/centos major version. The
# io.openshift.os.streamclass label is used by the MCO to later
# select the right image stream when multiple major versions coexist.
STREAM_CLASS=rhel-10

# Used by the generate-labels script
IMAGE_NAME=openshift/ose-rhel-coreos-10
IMAGE_CPE=cpe:/a:redhat:openshift:5.1::el10

# The names of the yum repos to use for the node image build.
YUM_REPO_NAMES=rhel-10.2-baseos,rhel-10.2-appstream,rhel-10.2-early-kernel,rhel-10.2-fast-datapath,rhel-10.2-server-ose-5.1

# The extra yum repos (on top of the YUM_REPO_NAMES above) to use for
# the extensions image build.
#
# - rhel-10.2-highavailability -> two-node-ha extension
# - rhel-10.2-nfv -> kernel-rt extension (x86_64 only)
#
# All other extensions can be pulled from the list of yum repos above.
EXTENSIONS_YUM_REPO_NAMES=rhel-10.2-highavailability,rhel-10.2-nfv
