# This file is used from Jenkinsfile.treecompose to generate
# the "oscontainer" image which has an embedded ostree repo inside.
# It expects "repo" to exist in the current directory.
FROM registry.fedoraproject.org/fedora:28
RUN yum -y install ostree nginx && yum clean all
COPY repo /srv/repo
# Keep this in sync with Dockerfile
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html subdomain.css /srv/repo/
EXPOSE 8080
CMD ["nginx", "-c", "/etc/nginx/nginx.conf"]
