#!/bin/bash

set -xeuo pipefail

LATEST_OPENSHIFT_REPO=`curl https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/.latest-rpms`

echo "[openshift]
name=openshift
baseurl=${LATEST_OPENSHIFT_REPO}
type=rpm
enabled=1
gpgcheck=0" > openshift.repo

REPOURL_PREFIX=http://rpm-mirror-ci.svc.ci.openshift.org/

curl -L --remote-name-all \
     ${REPOURL_PREFIX}/rhel-7.5-server{,-optional,-extras}.repo \
     ${REPOURL_PREFIX}/rhel-7.5-atomic.repo \
     ${REPOURL_PREFIX}/docker.repo
