#!/bin/bash
## kola:
##   exclusive: true
##   additionalDisks: ["1G:channel=nvme,serial=    foobar"]
##   platforms: qemu
##   # qemu on s390x does not support nvme emulation
##   architectures: "!s390x"
##   description: Verify that we are compatible with the old symlinks
##     for NVME disks.
##     https://github.com/openshift/os/pull/1243

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# the canonical symlink
s=/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_____foobar
if ! test -L "${s}"; then
    fatal "missing canonical symlink ${s}"
fi

# the compat symlink
s=/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl__foobar
if ! test -L "${s}"; then
    fatal "missing compat symlink ${s}"
fi

ok "nvme compat symlink"
