#!/bin/bash
## kola:
##   exclusive: true
##   additionalDisks: ["1G:channel=nvme,serial=    foobar"]
##   platforms: qemu
#
# By default coreos-generate-iscsi-initiatorname.service is active on RHCOS,
# inactive on FCOS
# https://github.com/openshift/os/pull/453

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# the canonical symlink
s=/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl_____foobar
if ! test -L "${s}"; then
    fatal "missing canonical symlink ${s}"
fi

# the compat symlink
s=/dev/disk/by-id/nvme-QEMU_NVMe_Ctrl__foobar
if ! test -L "${s}"; then
    fatal "missing compat symlink ${s}"
fi

ok "nvme compat symlink"
