#!/bin/bash
set -euo pipefail

# See also rhcos-growpart.service.
# This service duplicates the FCOS growpart which is
# done in the initramfs; it will likely go away once
# we rework to use Ignition LUKS.  See
# https://github.com/coreos/fedora-coreos-config/pull/503#discussion_r449240871
# https://github.com/coreos/fedora-coreos-tracker/issues/18

path=$1
shift

majmin=$(findmnt -nvr -o MAJ:MIN "$path")

# Detect if the rootfs is on a luks container and map
# it to the underlying partition. This assumes that the
# LUKS volumes is housed in a partition.
dmlinear=0
cryptsetup=0
dm_name=""
src=$(findmnt -nvr -o SOURCE "$path")
if [[ "${src}" =~ /dev/mapper ]]; then
    dm_name=$(dmsetup info ${src} -C -o name --noheadings) || true
    if [ "${dm_name}" == "coreos-luks-root-nocrypt" ]; then
        majmin=$(dmsetup table ${dm_name} | cut -d " " -f4)
        dmlinear=1
    elif [[ "$(dmsetup info ${dm_name} -C -o uuid --noheadings)" =~ "CRYPT-LUKS2" ]]; then
        majmin=$(dmsetup table ${dm_name} | cut -d " " -f7)
        cryptsetup=1
    fi
fi

devpath=$(realpath "/sys/dev/block/$majmin")
partition=$(cat "$devpath/partition")
parent_path=$(dirname "$devpath")
parent_device=/dev/$(basename "${parent_path}")

# TODO: make this idempotent, and don't error out if
# we can't resize.  Note in the dm-linear case we
# resized the partition in coreos-cryptfs.
if [ "${dmlinear}" != "1" ]; then
    growpart "${parent_device}" "${partition}" || true
fi

if [ "${cryptsetup}" -eq 1 ]; then
    source /usr/libexec/coreos-cryptlib "${parent_device}${partition}"
    clevis_key | cryptsetup resize "${dm_name}" -
fi

# See https://github.com/ostreedev/ostree/pull/1767
test -w /sysroot || mount -o remount,rw /sysroot
# this part is already idempotent
xfs_growfs /sysroot

touch /var/lib/coreos-growpart.stamp
