#!/bin/bash
## kola:
##   tags: "needs-internet"
##   timeoutMin: 30
##   description: Verify replacing the current kernel with an 
##     older centos kernel and replacing with kernel-rt.

set -euo pipefail

. $KOLA_EXT_DATA/commonlib.sh

# Execute a command verbosely, i.e. echoing its arguments to stderr
runv () {
    ( set -x ; "${@}" )
}

basearch=$(arch)
rhelver=$(. /usr/lib/os-release && echo "${RHEL_VERSION}")
major=$(echo "${rhelver}" | cut -f 1 -d .)
baseurl=
case "${major}" in
    8)
        # TODO: why the heck does centos only support insecure http?!?
        # TODO: Fix centos8 path
        baseurl=http://mirror.centos.org/centos/8-stream/
        repo_url=??
        target_kver=$(runv curl -sSLf ${baseurl}BaseOS/${basearch}/os/Packages/ | runv grep -o 'href=".*">' | runv grep -Po '(?<=kernel-core-).*?\.el8' | runv head -1)
        target_kver_rt=$(runv curl -sSLf ${baseurl}RT/${basearch}/os/Packages/ | runv grep -o 'href=".*">' | runv grep -Po '(?<=kernel-rt-core-).*?\.el8' | runv tail -1)
        ;;
    9)
        # TODO: why the heck does centos only support insecure http?!?
        baseurl=http://mirror.stream.centos.org/9-stream/
        repo_url=https://raw.githubusercontent.com/openshift/os/bf4383e4929ad9abb67d508a7ffa7cf45e8de5ca/c9s.repo
        target_kver=$(runv curl -sSLf ${baseurl}BaseOS/${basearch}/os/Packages/ | runv grep -o 'href=".*">' | runv grep -Po '(?<=kernel-core-).*?\.el9' | runv head -1)
        target_kver_rt=$(runv curl -sSLf ${baseurl}RT/${basearch}/os/Packages/ | runv grep -o 'href=".*">' | runv grep -Po '(?<=kernel-rt-core-).*?\.el9' | runv tail -1)
        ;;
    *)  fatal "Unhandled RHEL_VERSION=${rhelver}"
        ;;
esac

case "${AUTOPKGTEST_REBOOT_MARK:-}" in
"")
    echo "Testing overriding with previous CentOS Stream kernel"
    kver=$(uname -r)
    if test "${kver}" = "${target_kver}"; then
        fatal "Already in ${target_kver}"
    fi
    tmpdir=$(mktemp -d -p /var/tmp)
    pushd "${tmpdir}"
    runv curl -sSLf --remote-name-all "${baseurl}/BaseOS/${basearch}/os/Packages/kernel"{,-core,-modules,-modules-extra,-modules-core}"-${target_kver}.${basearch}.rpm"
    runv rpm-ostree override replace ./*.rpm
    popd
    rm "${tmpdir}" -rf
    runv /tmp/autopkgtest-reboot 1
    ;;
1)
    case $(uname -r) in
        "${target_kver}.${basearch}")
            echo "ok kernel override"
            ;;
        *)
            runv uname -r
            runv rpm -q kernel
            fatal "Failed to apply kernel override to ${target_kver}"
            ;;
    esac

    echo "Testing overriding with CentOS Stream RT kernel"
    case $basearch in
        x86_64)
            tmpdir=$(mktemp -d -p /var/tmp)
            pushd "${tmpdir}"
            #setup repos
            runv rm -rf /etc/yum.repos.d/*
            runv curl -v "${repo_url}" -o /etc/yum.repos.d/cs.repo
            runv sed -i 's/gpgcheck=1/gpgcheck=0/g' /etc/yum.repos.d/cs.repo
            runv rpm-ostree override reset -a
            args=(--install kernel-rt)
            runv rpm-ostree override remove kernel{,-core,-modules,-modules-extra,-modules-core} "${args[@]}"
            rm "${tmpdir}" -rf
            runv /tmp/autopkgtest-reboot 2
            ;;
        *) echo "note: no kernel-rt for $basearch"; exit 0
            ;;
    esac
    ;;
2)
    case $(uname -r) in
        "${target_kver_rt}.${basearch}+rt") echo "ok kernel-rt" ;;
        *)
           uname -r
           rpm -q kernel-rt
           fatal "Failed to apply kernel override to ${target_kver_rt}"
        ;;
    esac
    ;;
*)
    fatal "Unhandled reboot mark ${AUTOPKGTEST_REBOOT_MARK:-}"
    ;;
esac

echo ok
