#!/bin/bash
## kola:
##   description: Verify rpm-ostreed.service works when invoking
##      `rpm-ostree status` frequently.
##      https://github.com/coreos/rpm-ostree/pull/3523/commits/0556152adb14a8e1cdf6c5d6f234aacbe8dd4e3f

set -euo pipefail

for x in $(seq 10); do rpm-ostree status >/dev/null; done
echo ok
