#!/usr/bin/bash
set -xeuo pipefail

# Parse arguments and mount the image.
dest=$1; shift
img=$1; shift
rm ${dest} -rf
mkdir -p ${dest}/containers
# This ensures that we have container storage on overlayfs
# on the host.
containers_storage=/var/lib/containers
rm -rf ${containers_storage} && mkdir ${containers_storage}
mount --bind ${dest}/containers ${containers_storage}

skopeo inspect docker://${img}
podman pull ${img}
cid=$(podman run --net=host -d --name oscontainer --entrypoint sleep ${img} infinity)
ln -sf $(podman mount ${cid})/srv/repo ${dest}/repo
