# This extracts the OCI archive from the cosa-build image build, injects it
# into the build context, and then uses that OCI archive as this image.
# This makes use of the following:
# - OpenShift Image Builds allows one to pass in a path from another container
# image. It places this under /tmp/build/inputs/<path>. See:
# https://github.com/openshift/builder/blob/37525a77fa07e26c420962dee47193d672ef0b35/pkg/build/builder/common.go#L72
# - Buildah allows one to use oci-archive as a transport. See:
# https://www.redhat.com/sysadmin/7-transports-features
# - Utilizing the above features in concert with one another and using an
# absolute path to refer to the OCI archive in the build context allows us
# to "import" the OCI archive into the CI ImageStream.
FROM oci-archive:/tmp/build/inputs/magic/cosa/builds/latest/x86_64/rhcos.x86_64.ociarchive
