#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify we should not have 50-azure-ptp.rules.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

if [ -e /usr/lib/udev/rules.d/50-azure-ptp.rules ] && \
    grep ptp_hyperv /usr/lib/udev/rules.d/50-udev-default.rules; then
  fatal "50-udev-default.rules includes ptp_hyperv symlink; drop 50-azure-ptp.rules"
fi
