#!/bin/bash
# kola: { "exclusive": false }
set -xeuo pipefail

fatal() {
    echo "$@" >&2
    exit 1
}

if [ -e /usr/lib/udev/rules.d/50-azure-ptp.rules ] && \
    grep ptp_hyperv /usr/lib/udev/rules.d/50-udev-default.rules; then
  fatal "50-udev-default.rules includes ptp_hyperv symlink; drop 50-azure-ptp.rules"
fi
