#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that packages coming from the rhaos
##     branches match the OpenShift version.
##     This is RHCOS only.

set -xeuo pipefail

# shellcheck source=../data/commonlib.sh
. "$KOLA_EXT_DATA"/commonlib.sh

# source the environment variables to get OPENSHIFT_VERSION
source /etc/os-release

rpm -qa | grep "rhaos" > /tmp/rhaos-packages.txt

if grep -v "rhaos${OPENSHIFT_VERSION}" /tmp/rhaos-packages.txt; then
    fatal "Error: rhaos packages do not match OpenShift version"
fi
