#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that packages coming from the rhaos
##     branches match the OpenShift version.
##     This is RHCOS only.

set -xeuo pipefail

# shellcheck source=../data/commonlib.sh
. "$KOLA_EXT_DATA"/commonlib.sh

# source the environment variables to get OPENSHIFT_VERSION
source /etc/os-release

# These are packages that are known to not match the
# targeted version of openshift. Exlude them from the test.
RHAOS_PACKAGE_EXCEPTIONS=(
    # toolbox doesn't always match the target ocp version because it
    # is included in the base-image which spans multiple versions
    toolbox
    # cri-o hasn't been built for 4.22 yet
    cri-o
    # conmon currently is missing 4.19+ vesions of the package
    conmon-rs
)

exception_pattern=$(echo ${RHAOS_PACKAGE_EXCEPTIONS[@]} | tr " " "|")

# Use `|| true` here to allow situations where RHAOS_PACKAGE_EXCEPTIONS contains every
# rhaos package in the image, which would otherwise cause `grep -Ev` to fail the test.
rpm -qa | grep "rhaos" | grep -Ev "${exception_pattern}" > /tmp/rhaos-packages.txt || true

if grep -v "rhaos${OPENSHIFT_VERSION}" /tmp/rhaos-packages.txt; then
    fatal "Error: rhaos packages do not match OpenShift version"
fi
