#!/bin/bash
# kola: { "exclusive": false }
# Check that the OS version (C9S, RHEL 9.0) matches the version stored in
# /etc/os-release
set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

ocp_version="$(source /etc/os-release; echo "${VERSION}")"
variant="$(source /etc/os-release; echo "${ID}")"
case "${variant}" in
    "scos")
        osver="$(source /usr/lib/os-release.stream; echo "${VERSION_ID}")"
        ;;
    "rhcos")
        osver="$(source /usr/lib/os-release.rhel; echo "${VERSION_ID}" | sed 's/\.//')"
        ;;
    "*")
        fatal "Unknown variant"
esac
if [[ "${osver}" != "$(echo "${ocp_version}" | awk -F "." '{print $2}')" ]]; then
  fatal "Error: OS version and /etc/os-release version do not match"
fi
