#!/bin/bash
## kola:
##   exclusive: false
##   description: Verify that only packages from the RHEL major
##     version are included.

set -xeuo pipefail

. $KOLA_EXT_DATA/commonlib.sh

variant="$(source /etc/os-release; echo "${ID}")"
case "${variant}" in
    "centos")
        osver="$(source /etc/os-release; echo "${VERSION_ID}")"
        ;;
    "scos")
        osver="$(source /usr/lib/os-release.stream; echo "${VERSION}")"
        ;;
    "rhel")
        osver="$(source /etc/os-release; echo "${VERSION_ID}" | cut -d. -f1 )"
        ;;
    "rhcos")
        osver="$(source /usr/lib/os-release.rhel; echo "${VERSION}" | cut -d. -f1 )"
        ;;
    "*")
        fatal "Unknown variant"
esac

for pkg in $(rpm -qa); do
    name="$(rpm -q --queryformat='%{NAME}' "${pkg}")"
    # See https://bugzilla.redhat.com/show_bug.cgi?id=2115815
    if [[ "${name}" == "shim-x64" ]] || [[ "${name}" == "shim-aa64" ]]; then
        continue
    fi
    # Weirdly, querying the libgcc package on RHEL 8 returns the result twice
    # so let's read only the first answer
    release="$(rpm -q --queryformat='%{RELEASE}' "${pkg}" | grep -oP 'el\s*\K\d+' | head -1)"
    if [[ "${release}" != "${osver}" ]]; then
        fatal "Found packages '${name}' with release version '${release}' that does not match the OS current version '${osver}'"
    fi
done
